_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 30
                - 41
                - 55
            "2":
                - 1
                - 30
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.14
            "5": 0.19.7
            "8":
                - 2
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
action_type:
    value: part-orientation, tuple
batch_size:
    value: 16
buffer_size:
    value: 20000
criterion:
    value: energy-diff
device:
    value: cuda
epsilon:
    value: 0.01
gamma:
    value: 1
hidden_dim:
    value: 128
lr:
    value: 2e-05
minimal_size:
    value: 600
num_episodes:
    value: 10000
target_update:
    value: 5
time:
    value: "2025-02-28 12:33:35.838837"
