_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.14
        t:
            "1":
                - 1
                - 30
                - 41
                - 55
            "2":
                - 1
                - 30
                - 41
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.14
            "5": 0.19.7
            "8":
                - 2
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
actions_type:
    value: part-orientation-batch, tensor
criterion:
    value: energy-diff
device:
    value: cuda
gamma:
    value: 1
hidden_dim:
    value: 128
lr:
    value: 5e-05
max_batch_num:
    value: 20
max_orientation_num:
    value: 7
max_part_type:
    value: 20
num_episodes:
    value: 10000
time:
    value: "2025-03-12 11:58:49"
