general_cfg:
  algo_name: DQN 
  env_name: gym
  device: cpu 
  mode: train 
  collect_traj: false 
  n_interactors: 1 
  load_checkpoint: false
  load_path: Train_single_SingleSLM_DQN_20240819
  load_model_step: best 
  max_episode: -1 
  max_step: 20 
  seed: 1 
  online_eval: true 
  online_eval_episode: 10 
  model_save_fre: 500

algo_cfg:
  action_space:
    type: [vector, vector]
    size: [[20], [7]]
  obs_space:
    type: [image, vector, vector]
    size: [[1, 224, 224], [3], [140]]

  branch_layers:
    - name: view
      layers:
      - layer_type: conv2d
        in_channel: 1
        out_channel: 16 
        kernel_size: 4
        stride: 2
        activation: relu
      - layer_type: pooling
        pooling_type: max2d
        kernel_size: 2
        stride: 2
        padding: 0
      - layer_type: flatten
      - layer_type: norm
        norm_type: LayerNorm
        normalized_shape: 512
      - layer_type: linear
        layer_size: [128]
        activation: relu
    - name: lwh
      layers:
      - layer_type: linear
        layer_size: [32]
        activation: relu
      - layer_type: linear
        layer_size: [32]
        activation: relu
    - name: parts
      layers:
      - layer_type: linear
        layer_size: [256]
        activation: relu
      - layer_type: linear
        layer_size: [256]
        activation: relu
  merge_layers:
    - layer_type: linear
      layer_size: [256]
      activation: relu
    - layer_type: linear
      layer_size: [256]
      activation: relu

  batch_size: 16
  buffer_type: REPLAY_QUE
  max_buffer_size: 10000
  epsilon_decay: 1000
  epsilon_end: 0.01
  epsilon_start: 0.99
  gamma: 0.95
  lr: 0.001
  target_update: 4

env_cfg:
  id: SingleSLM-v0
  render_mode: null